window:
  dynamic_padding: true
  padding:
    x: 5
    y: 5

font:
  size: 13.0
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic

draw_bold_text_with_bright_colors: true

background_opacity: 0.8

cursor:
  style: Beam
  thickness: 0.3

live_config_reload: true

mouse:
  url:
    launcher: firefox
