[directory]
truncation_length = 4
truncate_to_repo = false

[git_branch]
style = "bold green"

#[memory_usage]
#disabled = false
#show_percentage = true
#show_swap = true
#threshold = -1
#symbol = "memory "

[rust]
symbol = " "

[python]
symbol = "  "
pyenv_version_name = true
scan_for_pyfiles = true
python_binaries = ["python3.9", "python3.8", "python3"] 
disabled = false

[time]
disabled = true
use_12hr = true


