[directory]
truncation_length = 4
truncate_to_repo = false

[git_branch]
style = "bold green"
symbol = " "

[git_status]
# ahead = "↑ ${count}"
# behind = "↓ ${count}"
# diverged = "${ahead_count}↕${behind_count}"
# conflicted = "! ${count}"
# untracked = "? ${count}"
# stashed = "$ ${count}"
# modified = "~ ${count}"
# staged = "+ ${count}"
# renamed = "> ${count}"
# deleted = "- ${count}"

[golang]
symbol = " "

[rust]
symbol = " "

[python]
symbol = "  "
pyenv_version_name = true
scan_for_pyfiles = true
python_binaries = ["python3.9", "python3.8", "python3"] 

